In [1]:
"""
End-to-end RDR run over entity tokens in WikiNeural (English).

Usage
-----
python -m scripts.run_rdr_llama_ent --layer 27 --k 8 --t 10 --split test_en
python -m scripts.run_rdr_llama_ent --layer 27 --k 8 --t 10 --split test_en
"""

import sys
sys.path.insert(0, '/data8/baek/dehallu/RDR')
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

import argparse
import numpy as np

from models.language.llama_rdr          import LlamaRDR
from models.language.config_utils       import getconfigs_entities, config_dist, getconfigs
from models.rdr                         import RDR
from utils.visualize_text           import visualize_entity
from data.nlp import sst2
from data.nlp import wikineural_ent, hallu, pararel

In [2]:
class Args:
    def __init__(self):
        self.layer = 27
        self.k = 8
        self.t = 10
        self.split = "test_en"
        self.batch_size = 8
        self.dataset = "entity"
        self.model_name = "meta-llama/Llama-3.1-8B-Instruct"  #meta-llama/Llama-3.1-8B-Instruct, meta-llama/Llama-3.2-1B

args = Args()

In [3]:
args.dataset = "entity"

In [4]:

# 0  Load dataset & model
if args.dataset == "wikineural_ent":
    dataset = wikineural_ent.get_split(args.split)
elif args.dataset == "hallucination":
    dataset = hallu.get_split(args.split)
elif args.dataset == "sst2":
    dataset = sst2.get_split(args.split)
elif args.dataset == "entity":
    # dataset = hallu.get_split(args.split, entity=True)
    assert args.model_name == "meta-llama/Llama-3.1-8B-Instruct"  #meta-llama/Llama-3.1-8B-Instruct, meta-llama/Llama-3.2-1B
    # file path : RDR/data/nlp/pararel_llama31_predictions.jsonl
    dataset = pararel.get_split(args.split, entity_option="entity only")
else:
    raise ValueError(f"Unknown dataset: {args.dataset}")

print(f"Dataset: {args.dataset}, Split: {args.split}, Size: {len(dataset)}")

Add offsets: 100%|██████████| 157656/157656 [00:13<00:00, 11630.04rows/s]

Dataset: entity, Split: test_en, Size: 132606


In [5]:
args.layer = 15
args.model_name = "meta-llama/Llama-3.1-8B-Instruct"  #meta-llama/Llama-3.1-8B-Instruct, meta-llama/Llama-3.2-1B

In [6]:
model   = LlamaRDR(model_name=args.model_name, target_layer=args.layer, capture_seq_pos=None)  # keep full seq

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [7]:
count = 0
from pprint import pprint
pprint(dataset[:1])  # Print the first instance to check the structure
entity  = "Eiffel Tower"  # Example entity to count in the dataset
entity_set = set()
for d in dataset:
    # print(type(d))
    if d["entity"] == entity:
        pprint(d)
        count += 1
    if d["entity"] not in entity_set :
        entity_set.add(d["entity"])
print(f"Number of instances with entity '{entity}': {count}")
print(f"Total instances in dataset: {len(dataset)}")
print(f"Total unique entities in dataset: {len(entity_set)}")
print(f"Sample of unique entities: {list(entity_set)[:10]}")  # Print first 10 unique entities

[{'char_span': (1, 11),
  'correct': True,
  'decoded_entity': ' Antarctica',
  'entity': 'Antarctica',
  'entity_token_idx': 1,
  'prediction': 'Antarctica',
  'relation': '[X] is located in [Y].',
  'sentence': ' Antarctica',
  'subject': 'Lavoisier Island'}]
Number of instances with entity 'Eiffel Tower': 0
Total instances in dataset: 132606
Total unique entities in dataset: 1390
Sample of unique entities: ['Glasgow', 'gospel', 'jury', 'Shanghai', 'Nairobi', 'ear', 'majority', 'habitat', 'Damascus', 'film']


In [8]:
# 1  Pick a random target instance
rand_target = np.random.randint(len(dataset))
print(f"len: {len(dataset)}")
rand_target =5  # for debugging
print(f"Target sample index: {rand_target}  | entity = {dataset[rand_target]['entity']}")
print(f"Target sample: {dataset[rand_target]['sentence']}")

len: 132606
Target sample index: 5  | entity = Antarctica
Target sample:  Antarctica


In [9]:
# make dataset a set of entities
entity_set = set()
filter_dataset = []
id = 0
for d in dataset:
    if d["entity"] not in entity_set:
        entity_set.add(d["entity"])
        d["id"] = "f-"+str(id)
        id += 1
        filter_dataset.append(d)
print(f"Total unique entities in filtered dataset: {len(entity_set)}")
dataset = filter_dataset

Total unique entities in filtered dataset: 1390


In [10]:

# 2  Gather matrices
if args.dataset == "sst2":
    feats, configs = getconfigs(dataset, model)
else:
    feats, configs = getconfigs_entities(dataset, model,
                                        batch_size=args.batch_size)

Extracting features and configs: 100%|██████████| 174/174 [00:06<00:00, 25.01it/s]


In [ ]:
# mu = feats.mean(axis=0)
# std = feats.std(axis=0)
# import numpy as np

# # --- assume `feats` ndarray already exists in the notebook ---
# if 'feats' not in globals():
#     raise NameError("`feats` ndarray not found. Run getconfigs_entities first.")

# min_val = feats.min()
# max_val = feats.max()

# within_range   = np.logical_and(feats >= -1., feats <=  1.)
# num_total      = feats.size
# num_in_range   = within_range.sum()
# num_out_of_rng = num_total - num_in_range

# print(f"min activation = {min_val:.4f}")
# print(f"max activation = {max_val:.4f}")
# print(f"in [-1, 1]     : {num_in_range:,}  ({num_in_range/num_total:.2%})")
# print(f"outside range  : {num_out_of_rng:,}  ({num_out_of_rng/num_total:.2%})")


min activation = -2.3535
max activation = 8.7656
in [-1, 1]     : 5,678,067  (99.73%)
outside range  : 15,373  (0.27%)


In [12]:
EDGE_START = -6.0
EDGE_END = 6.0
EDGE_STEP = 0.1
edges = np.arange(EDGE_START, EDGE_END + EDGE_STEP, EDGE_STEP)
n_bins = len(edges)
counts = np.zeros((4096, n_bins), dtype=np.int64)

idx = np.searchsorted(edges, feats, side='right') - 1
idx = np.clip(idx, 0, len(edges) - 1)
for d in range(4096):
    np.add.at(counts[d], idx[:, d], 1)

import matplotlib.pyplot as plt
from IPython.display import clear_output
def show_neuron(n):
    c = counts[n]
    plt.bar(edges[:], c, width=edges[1]-edges[0], align="edge")
    plt.title(f"Layer{args.layer} Neuron {n}")
    plt.yscale("log")
    plt.show()
import time

# for n in range(4096):
#     clear_output(wait=True)
#     print(f"Showing neuron {n}...")
#     show_neuron(n)
#     time.sleep(1)

In [13]:
# # feats: (N, 4096)
# tail_mask = np.abs(feats) > 2.0          # |x|>2 를 꼬리로 정의
# tail_ratio = tail_mask.mean(axis=0)      # (4096,)

# # 꼬리 많은 상위 20개 뉴런 확인
# top = tail_ratio.argsort()[::-1][:20]
# for n in top:
#     print(f"Neuron {n:4d}  tail_ratio={tail_ratio[n]*100:.2f}%")


In [14]:
thr_vec = np.quantile(feats, 0.995, axis=0)   # 상위 0.5% on
bin_conf = (feats > thr_vec).astype(int)


In [15]:
def plot_ccdf(neuron_id):
    vals = np.sort(np.abs(feats[:, neuron_id]))[::-1]
    p = np.arange(len(vals))/len(vals)
    plt.loglog(vals, p)
    plt.xlabel("|activation|"); plt.ylabel("P(|X|>x)")
    plt.title(f"Layer15 • Neuron {neuron_id} CCDF")
    plt.grid(True); plt.show()


In [16]:
# plot_ccdf(4055)  # plot for neuron 0
# plot_ccdf(4056)  # plot for neuron 1

In [17]:
print(configs[:5])
print(configs[-5:])

[[1 1 0 ... 1 1 0]
 [1 0 0 ... 1 0 1]
 [0 0 0 ... 1 1 1]
 [1 0 0 ... 1 1 1]
 [1 0 0 ... 1 0 1]]
[[0 0 1 ... 1 1 1]
 [0 0 0 ... 0 0 1]
 [0 0 1 ... 1 0 1]
 [0 1 1 ... 1 0 1]
 [0 0 1 ... 1 0 1]]


In [18]:


# 3  Distances
dists      = config_dist(configs, rand_target)
neighbours = np.argsort(dists)
print(f"Nearest neighbours: {neighbours[:15]} out of {len(neighbours)}")
for i in neighbours[:5]:
    print(f"  {dataset[i]['sentence']}  | entity = {dataset[i]['entity']}")
# check distances
print(f"Distance to target: {dists[rand_target]:.4f}")
print(f"Distance to nearest neighbour: {dists[neighbours[0]]:.4f}")
print(f"Distance to second nearest neighbour: {dists[neighbours[1]]:.4f}")
print(f"Distance to  neighbour: {dists[neighbours[-1]]:.4f}")

Nearest neighbours: [   5 1158  158   79   13  159  122   77  388 1169  117  287  133   25
  240] out of 1390
   galaxy  | entity = galaxy
   genome  | entity = genome
   glacier  | entity = glacier
   planet  | entity = planet
   lake  | entity = lake
Distance to target: 0.0000
Distance to nearest neighbour: 0.0000
Distance to second nearest neighbour: 1307.0000
Distance to  neighbour: 1920.0000


In [19]:
args.k = 5
args.t = 3

In [20]:
from models.rdr                         import RDR
# 4  RDR
rdr   = RDR(neighbours, configs)
samp, neurons, states = rdr.selection(k=args.k, t=args.t)

3 decision boundaries are used for constructing relaxed decision region.
The number of samples included in the Relaxed Decision Region: 30


In [21]:
# 5  Visualise
print(f"Target: {dataset[rand_target]['sentence']}  | entity = {dataset[rand_target]['entity']}")
visualize_entity(samp, dataset, print_max=25)

Target:  galaxy  | entity = galaxy
 genome
 head
 Judaism
 flour
 fountain
 France
 electro
 galaxy
 tree
 flagship
 flower
 metabolism
 molecule
 cell
 gospel
 Netherlands
 genus
 yacht
 Italy
 morphology
 lake
 Word
 glacier
 Belgium
 skiing


In [23]:
# Netherlands f-876
# France f-620
# Spain f-519
# Catalonia f-979
# flower f-912
# Korea f-1352
# Seoul f-423

# for i, n in enumerate(dataset):
#     if n["entity"] == "Seoul":
#         print(n["id"])
target = "Spain"
target_idx = 519
features= [876, 620, 519, 979, 912, 1352, 423]  # Netherlands, France, Spain, Catalonia, flower, Korea, Seoul
features.remove(target_idx)  # remove target from features
dists = config_dist(configs, target_idx=target_idx, feature_idx=features)  # Spain
new_configs = configs[features,:]  # get new configs for features
print(new_configs)
print(len(features), len(dists))
print(f"Target: {dataset[target_idx]['sentence']}  | entity = {dataset[target_idx]['entity']}")
for i, d in enumerate(dists):
    print(f"  {dataset[features[i]]['entity']}  | dist = {d:.4f}")

[[1 1 0 ... 1 1 0]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 0 1]
 [1 0 0 ... 0 1 0]
 [1 1 0 ... 1 1 1]
 [0 1 0 ... 1 0 1]]
6 6
Target:  Spain  | entity = Spain
  Netherlands  | dist = 1175.0000
  France  | dist = 952.0000
  Catalonia  | dist = 1439.0000
  flower  | dist = 1550.0000
  Korea  | dist = 1452.0000
  Seoul  | dist = 1468.0000


In [40]:
from sklearn.metrics import pairwise_distances
from sklearn.cluster import AgglomerativeClustering

# (N, D) 이진 행렬 `configs`
dist = pairwise_distances(configs, metric='hamming')   # (N, N) 실수 [0~1]
# 정수 해밍 거리가 필요하면  dist_int = (dist * configs.shape[1]).astype(int)
K =50
clu = AgglomerativeClustering(
        n_clusters=K,          # 또는 distance_threshold=…
        metric='precomputed',  # 거리 행렬 직접 사용
        linkage='average')     # complete/single/ward 중 선택
labels = clu.fit_predict(dist)
labels = labels.tolist()


In [31]:
from sklearn_extra.cluster import KMedoids
kmed = KMedoids(n_clusters=K, metric='manhattan', init='k-medoids++',
                n_jobs=-1, random_state=0)
labels = kmed.fit_predict(configs)


ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [ ]:
from sklearn.cluster import DBSCAN
db = DBSCAN(eps=5, min_samples=10, metric='manhattan', n_jobs=-1)
labels = db.fit_predict(configs)      # -1 = 노이즈
print(labels)


[-1 -1 -1 ... -1 -1 -1]


In [36]:
from sklearn.neighbors import NearestNeighbors
from sklearn.cluster import SpectralClustering
import scipy.sparse as sp

k = 20
nbrs = NearestNeighbors(n_neighbors=k, metric='manhattan',
                        n_jobs=-1).fit(configs)
dist, idx = nbrs.kneighbors(configs)

# 인접 행렬 (sparse)
rows = np.repeat(np.arange(configs.shape[0]), k)
adj  = sp.csr_matrix((np.ones_like(rows), (rows, idx.ravel())),
                     shape=(configs.shape[0], configs.shape[0]))
adj = adj.maximum(adj.T)   # 대칭화

spec = SpectralClustering(
          n_clusters=K, affinity='precomputed',
          assign_labels='kmeans', random_state=0)
labels = spec.fit_predict(adj)


In [37]:
print(labels)

[41 49 49 ... 40 32 17]


In [41]:
print(f"Number of clusters: {len(set(labels))}")
print(f"Cluster labels: {set(labels)}")
# show clusters
for i in range(K):
    print(f"Cluster {i}:")
    # print(f"  Number of instances: {labels.count(i)}")
    print(f"  Entities:", end=' ')
    for j, l in enumerate(labels):
        if l == i:
            print(f"{dataset[j]['entity']}", end=', ')
    print("\n")

Number of clusters: 50
Cluster labels: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49}
Cluster 0:
  Entities: English, RNA, DNA, Unix, Internet, Java, Linux, England, Python, 

Cluster 1:
  Entities: tourism, proposition, measure, grammar, sentence, publishing, essay, syntax, 

Cluster 2:
  Entities: Antarctica, Asia, Africa, Europe, Americas, Hebrew, French, Irish, Armenian, Dutch, Chinese, Croatian, Fiat, iOS, hull, Catalan, German, manuscript, Vikings, port, manifold, iPhone, ITV, Scotland, Toronto, Vienna, Paris, Barcelona, Rome, Lahore, Belfast, Budapest, Melbourne, Lyon, Halifax, Tokyo, London, Montreal, Queensland, Sydney, Helsinki, Seoul, Detroit, Bangkok, Nebraska, Madrid, Bristol, Glasgow, Ukraine, Houston, Milan, Tehran, Atlanta, Thailand, Shanghai, Berlin, Taipei, Boston, Havana, Essex, Auckland, Chicago, Brunswick, Denver, Perth, Ha